//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: String,
    #[sea_orm(unique)]
    pub email: String,
    pub username: String,
    pub password: String,
    #[sea_orm(unique)]
    pub token: String,
    #[sea_orm(unique)]
    pub timestamp: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::favorite::Entity")]
    Favorite,
    #[sea_orm(has_many = "super::watch_state::Entity")]
    WatchState,
}

impl Related<super::favorite::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Favorite.def()
    }
}

impl Related<super::watch_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WatchState.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
